feat: remote webcomponents
onecx/onecx-shell-ui pull request #136
Opened 2024-06-19 07:49 UTC by markuczy

2024-06-19 07:50 UTC, markuczy commented on src/app/shell/services/routes.service.ts
> +        ) {
tmp workaround

2024-06-25 12:28 UTC, markuczy commented on src/app/shell/services/routes.service.ts
> +        mfeInfo: this.routeToMfeInfo(r, r.baseUrl),
change will be required in all uis once shell is udpated

2024-07-01 09:25 UTC, SchettlerKoehler requested changes

2024-07-01 09:25 UTC, SchettlerKoehler commented on src/app/app.component.ts
> +import { Component, NgZone, inject } from '@angular/core';
Why is this needed?

2024-07-01 09:26 UTC, markuczy commented on src/app/app.component.ts
> +import { Component, NgZone, inject } from '@angular/core';
its not needed anymore

2024-07-01 10:18 UTC, merged